# Generated by Django 5.2.7 on 2025-10-29 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='devices',
        ),
        migrations.AddField(
            model_name='joborder',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joborder',
            name='number_devices',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='operation',
            name='standard_time',
            field=models.PositiveIntegerField(help_text='Time in minutes'),
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=150, unique=True)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='api.device')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_instances', to='api.joborder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='device_instances',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='api.deviceinstance'),
        ),
        migrations.CreateModel(
            name='DeviceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Lower numbers run earlier')),
                ('minimum_output_override', models.PositiveIntegerField(blank=True, help_text='If set, use instead of operation.minimum_output', null=True)),
                ('standard_time_override', models.PositiveIntegerField(blank=True, help_text='If set, use instead of operation.standard_time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_operations', to='api.device')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_operations', to='api.operation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='operations',
            field=models.ManyToManyField(related_name='devices', through='api.DeviceOperation', to='api.operation'),
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_output', models.PositiveIntegerField(default=0)),
                ('total_actual_time_minutes', models.PositiveIntegerField(default=0)),
                ('total_standard_time_minutes', models.PositiveIntegerField(default=0)),
                ('productive_time_minutes', models.PositiveIntegerField(default=0)),
                ('available_time_minutes', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='api.device')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.joborder')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='api.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('device_serials', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('device_instances', models.ManyToManyField(blank=True, related_name='submissions', to='api.deviceinstance')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.joborder')),
                ('operations', models.ManyToManyField(blank=True, related_name='submissions', to='api.operation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceinstance',
            index=models.Index(fields=['serial'], name='api_devicei_serial_3096e1_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinstance',
            index=models.Index(fields=['device'], name='api_devicei_device__cd4e0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceoperation',
            unique_together={('device', 'operation')},
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['date'], name='api_perform_date_dee6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['job_order'], name='api_perform_job_ord_b43c62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together={('date', 'job_order', 'device', 'operation')},
        ),
    ]
